name: Build and Push to Artifact Registry (via key)

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: hochanhti
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/hochanhti/my-repo/my-image:latest .

      - name: Push image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/hochanhti/my-repo/my-image:latest
