name: learning ong udemy
on:
  push:
    branches:
      - stg
jobs:
  job_test:
    runs-on: ubuntu-latest
    steps:
      - name: test  
        run: |
          echo "ducgiang.ng"
          echo "${{ github.event }}"
