name: learning on udemy
on: 
  workflow_dispatch:
  push:
    branches:
      - stg
jobs:
  job_test:
    runs-on: ubuntu-latest
    steps:
      - name: test  
        run: |
          echo "ducgiang.ng"
          echo "${{ toJSON(github.event) }}"
